[project]
name = "sql-unit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "sqlparse>=0.5.3",
]

[dependency-groups]
dev = [
    "duckdb>=1.3.1",
    "pytest>=8.4.1",
]
